### ISSUE TITLE
System hung

### ISSUE THREAD

**Issue by dtchang** [atomistic-machine-learning/dtnn#2]
System hung after downloading data:
--
No database found at `data_dir\gdb9.db`. Should GDB-9 data be downloaded to that location? [y/N]y
INFO - Downloading GDB-9 data...
INFO - Done.
--

No message. No progress bar.

**Comment by dtchang** [comment]
It appears the system hung in the following code segment in load_data():
    tar = tarfile.open(tar_path)
    tar.extractall(raw_path)
    tar.close()
because
    logging.info('Parse xyz files...')
didn't get executed.

**Comment by dtchang** [comment]
I debugged. The system hung on
tar.extractall(raw_path)

**Comment by ktschuett** [comment]
Sorry for the long delay. Can you check whether the data was correctly downloaded to 'raw_path'? If yes, it is probably a system-specific issue. Perhaps your hard drive or memory is full?
