### ISSUE TITLE
Invariance 

### ISSUE THREAD

**Issue by VictorPulzz** [atomistic-machine-learning/dtnn#3]
Hello, excellent work done for you. Please tell me how you consider invariance of the atomic system with respect to rotation. If I rotate the coordinate system, then the calculations should not change. Thanks!

**Comment by VictorPulzz** [comment]
@ktschuett Can you help?

**Comment by ktschuett** [comment]
Hi, this is the case for DTNN as the prediction is done only based on distances between atoms, not absolute positions. Btw, the successor of DTNN, SchNet, can be found here: https://github.com/atomistic-machine-learning/schnetpack
